QuizzWebApp/Models/ChoiceTable.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizzWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiceTable
    {
        public int ID { get; set; }
        public int QuestionId { get; set; }
        public string ChoiceText { get; set; }
    
        public virtual QuestionTable QuestionTable { get; set; }
    }
}

QuizzWebApp/Models/QuestionTable.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizzWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionTable()
        {
            this.ChoiceTables = new HashSet<ChoiceTable>();
        }
    
        public int Id { get; set; }
        public string QuestionText { get; set; }
        public string Answer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChoiceTable> ChoiceTables { get; set; }
    }
}

QuizzWebApp/Models/QuizzModels.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizzWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbQuizzEntities : DbContext
    {
        public DbQuizzEntities()
            : base("name=DbQuizzEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChoiceTable> ChoiceTables { get; set; }
        public virtual DbSet<QuestionTable> QuestionTables { get; set; }
    }
}

QuizzWebApp/Models/QuizzModels.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Pepo\source\repos\QuizzWebApp\QuizzWebApp\Models\QuizzModels.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

QuizzWebApp/Models/QuizzModels.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

QuizzWebApp/ViewModels/ChoiceVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QuizzWebApp.ViewModels
{
    public class ChoiceVM
    {
        public int ChoiceID { get; set; }
        public string ChoiceText { get; set; }
    }
}

QuizzWebApp/ViewModels/QuestionVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QuizzWebApp.ViewModels
{
    public class QuestionVM
    {
        public int QuestionID { get; set; }
        public string QuestionText { get; set; }
        public string Anwser { get; set; }
        public string UserAnswer { get; set; }
        public ICollection<ChoiceVM> Choices { get; set; }
    }
}

QuizzWebApp/ViewModels/QuizzModeVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizzWebApp.ViewModels
{
    public class QuizzModeVM
    {
        public int Mode { get; set; }
        public IEnumerable<SelectListItem> Modes { get; set; }
    }
}

QuizzWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizzWebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

QuizzWebApp/Controllers/QuizzController.cs
using QuizzWebApp.Models;
using QuizzWebApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizzWebApp.Controllers
{
    public class QuizzController : Controller
    {
        public DbQuizzEntities dbContext = new DbQuizzEntities();

        // GET: Quizz
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult QuizzSettings()
        {
            QuizzModeVM modeList = new QuizzModeVM();
            modeList.Modes = new List<SelectListItem>()
            {
                new SelectListItem(){ Text="Yes or No", Value= "0"},
                new SelectListItem(){ Text="3 Choices", Value= "1"},
            };

            return View(modeList);
        }

        [HttpPost]
        public ActionResult QuizzSettings(QuizzModeVM quizMode)
        {
            Session["SelectedMode"] = quizMode.Mode;

            return RedirectToAction("QuizzView");
        }

        [HttpGet]
        public ActionResult QuizzView()
        {
            int selectedMode = (int)Session["SelectedMode"];

            Random rand = new Random();
            int toSkip = rand.Next(0, dbContext.QuestionTables.Count());
            var tmpQ = dbContext.QuestionTables.OrderBy(x => x.Id).Skip(toSkip).Take(1).First();
            QuestionVM question = new QuestionVM()
            {
                QuestionID = tmpQ.Id,
                QuestionText = tmpQ.QuestionText,
                Anwser = tmpQ.Answer,
                Choices = new List<ChoiceVM>()
            };

            foreach (var c in tmpQ.ChoiceTables)
            {
                question.Choices.Add(new ChoiceVM() { ChoiceID = c.ID, ChoiceText = c.ChoiceText });
            }

            return View(question);
        }
    }
}

QuizzWebApp/Views/Quizz/QuizzSettings.cshtml
@model QuizzWebApp.ViewModels.QuizzModeVM
@{
    ViewBag.Title = "Quizz Mode Selection";
}

@Styles.Render("~/Content/css")

<div class="container">
    <div class="SelQuiz">
        <div class="panel panel-default" style="width: 37%; margin: 20% 32%;">
            <div class="panel-heading">Select Quiz Mode</div>
            <div class="panel-body">
                @using (Html.BeginForm("QuizzSettings", "Quizz", FormMethod.Post))
                {
                    @Html.DropDownListFor(model => model.Mode, Model.Modes, new { @class = "form-control", @style = "margin-left:51px;" })<br />
                    <button type="submit" id="Enter" class="btn btn-success btn-lg" style="width:100%;"><span class="glyphicon glyphicon-ok"></span>   Let's GO </button>
                }
            </div>
        </div>
    </div>
</div>

QuizzWebApp/Views/Quizz/QuizzView.cshtml
@model QuizzWebApp.ViewModels.QuestionVM
@{
    ViewBag.Title = "Question";
    int countR = 0;
    int mode = (int)Session["SelectedMode"];
    Random rnd = new Random();
    int r = rnd.Next(Model.Choices.Count);
}

@Styles.Render("~/Content/css")



<div class="container">
    <div class="Quiz">
        @if (Model != null)
        {
            <div class="QuestionBlock" style="border: 1px solid #bdbdbd; width: 75%; border-radius: 4px; margin-top: 20px; background-color: lightblue; padding: 2px; align-items:center;justify-content:center">
                <div class="Question" style="padding: 1%;">
                    <h4 style="margin-top: 0.5%;margin-bottom:0.5%;"> <span class="label label-info">Question:</span> </h4>
                    <div style="display:inline;padding:2%;">@Model.QuestionText</div>
                </div>
                <div class="Choices" style="margin-left: 4%;">
                    @if (mode == 1)
                    {
                        foreach (var choice in Model.Choices)
                        {
                            <label class="radio-inline">
                                <input type="radio" name="inlineRadioOptions" id="@string.Format("{0}{1}", "inlineRadio", countR)" value="@choice.ChoiceText" style="margin-left: -16px;"> @choice.ChoiceText
                            </label><br />
                            countR++;
                        }
                    }
                    else if (mode == 0)
                    {

                        <div style="display:inline;padding:2%;text-align:center">@Model.Choices.ElementAt(r).ChoiceText</div>
                        <label class="radio-inline">
                            <input type="radio" name="inlineRadioOptions" id="inline1" value="1" style="margin-left: -16px;"> Yes<br>
                            <input type="radio" name="inlineRadioOptions" id="inline2" value="0" style="margin-left: -16px;"> No
                        </label><br />
                    }
                </div>
                <button type="button" onclick="CheckAnswer();" id="Enter" class="btn btn-success btn-sm" style="width:20%;margin-top:10px;margin-left:30px"><span class="glyphicon glyphicon-ok"></span>   Check answer </button>

                <script type="text/javascript">
                        var quizzMode = @mode;
                        var answer = "@Model.Anwser";

                        function CheckAnswer() {
                            if (quizzMode == 0) {
                                var correct = 0;
                                if (answer == "@Model.Choices.ElementAt(r)")
                                    correct = 1;

                                var userChoose = document.querySelector('input[name="inlineRadioOptions"]:checked').value.toLowerCase();
                                if (correct == userChoose) {
                                    alert("Good! Correct Answer is " + answer);
                                }
                                else {
                                    alert("Sorry! Wrong Answer! The correct one was " + answer);
                                }
                            }
                            else if (quizzMode == 1) {
                                var userChoose = document.querySelector('input[name="inlineRadioOptions"]:checked').value.toLowerCase();
                                if (answer == userChoose) {
                                    alert("Good! Correct Answer is " + answer);
                                }
                                else {
                                    alert("Sorry! Wrong Answer! The correct one was " + answer);
                                }
                            }

                            window.history.back();
                        }
                </script>
            </div>
        }
    </div>
</div>